# Generated by Django 3.2.23 on 2024-01-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('rating', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('upc', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.CharField(max_length=50)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category')),
            ],
        ),
    ]
