# Generated by Django 3.2.23 on 2024-02-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_books', models.IntegerField()),
                ('subscription_type', models.CharField(choices=[('one-off', 'One-off'), ('three_months', '3-months'), ('six_months', '6-months'), ('twelve_months', '12-months')], default='one-off', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
    ]
