# Generated by Django 3.2.23 on 2024-02-11 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_usersubscriptionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionoption',
            name='subscription_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions_options', to='subscriptions.subscriptionoption'),
        ),
        migrations.AlterField(
            model_name='usersubscriptionoption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
