# Generated by Django 3.2.23 on 2024-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20240211_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoption',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionoption',
            name='subscription_type',
            field=models.CharField(choices=[('one-off', 'One-off'), ('monthly', 'Monthly'), ('three_months', '3-months')], max_length=20),
        ),
    ]
