# Generated by Django 3.2.23 on 2024-03-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_rating'),
        ('subscriptions', '0005_auto_20240211_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic (2 books)'), ('standard', 'Standard (3 books)'), ('premium', 'Premium (4 books)')], default='basic', max_length=50)),
                ('number_of_books', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersubscriptionoption',
            name='calculated_price',
        ),
        migrations.RemoveField(
            model_name='usersubscriptionoption',
            name='subscription_option',
        ),
        migrations.AddField(
            model_name='usersubscriptionoption',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category'),
        ),
        migrations.AddField(
            model_name='usersubscriptionoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionoption',
            name='subscription_type',
            field=models.CharField(choices=[('one-off', 'One-off'), ('monthly', 'Monthly'), ('three_months', 'Every 3 Months')], default='one-off', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscriptionoption',
            name='selected_books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
        migrations.DeleteModel(
            name='SubscriptionOption',
        ),
        migrations.AddField(
            model_name='usersubscriptionoption',
            name='plan',
            field=models.ForeignKey(default='basic', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
    ]
