# Generated by Django 3.2.23 on 2024-04-13 12:09

from django.db import migrations


def add_subscription_options(apps, schema_editor):
    SubscriptionOption = apps.get_model('subscriptions', 'SubscriptionOption')
    Category = apps.get_model('books', 'Category')

    category1 = Category.objects.get(category='Childrens')
    category2 = Category.objects.get(category='Classics')
    category3 = Category.objects.get(category='Fantasy')
    category4 = Category.objects.get(category='Fiction')
    category5 = Category.objects.get(category='Horror')
    category6 = Category.objects.get(category='Humor')
    category7 = Category.objects.get(category='Nonfiction')
    category8 = Category.objects.get(category='Young Adult')

    # Define a list of new or updated subscription options
    new_or_updated_subscription_options = [
        {'category': category1, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4iCzG6iutubJZOJU77f13O'},
        {'category': category1, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4iQSG6iutubJZOXtUujVBf'},
        {'category': category1, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4iQSG6iutubJZOB14APK8l'},
        {'category': category1, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4j8LG6iutubJZOw3zVbU6J'},
        {'category': category1, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4iQSG6iutubJZOXtUujVBf'},
        {'category': category1, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4iQSG6iutubJZOBuH4JK8t'},
        {'category': category2, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4il0G6iutubJZOGcgqucJV'},
        {'category': category2, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4j1gG6iutubJZOC5CjBCZu'},
        {'category': category2, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4j1gG6iutubJZOx560VKiO'},
        {'category': category2, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4jAYG6iutubJZOtk5Ee28R'},
        {'category': category2, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4j1gG6iutubJZOpj4KrZ76'},
        {'category': category2, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4j1gG6iutubJZOp038AmYN'},
        {'category': category3, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4itEG6iutubJZORQSUEhdn'},
        {'category': category3, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4j4yG6iutubJZOO2UAnD5A'},
        {'category': category3, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4j4yG6iutubJZOKLJRs5tg'},
        {'category': category3, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4jDZG6iutubJZOppBmJ59h'},
        {'category': category3, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4jDZG6iutubJZOUdq9ZOph'},
        {'category': category3, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4jDZG6iutubJZO8ZD85FgR'},
        {'category': category4, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4itsG6iutubJZOir8Lppfd'},
        {'category': category4, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4jGKG6iutubJZOPlDnHB8B'},
        {'category': category4, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4jGKG6iutubJZOphY4877o'},
        {'category': category4, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4jGKG6iutubJZOSIQnZMBc'},
        {'category': category4, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4jGKG6iutubJZOkPLGFA7C'},
        {'category': category4, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4jGKG6iutubJZOxZd4xmkT'},
        {'category': category5, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4iunG6iutubJZOxbwNOQZK'},
        {'category': category5, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4k0UG6iutubJZOZljLY6Lr'},
        {'category': category5, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4k0UG6iutubJZOIGmoXCg3'},
        {'category': category5, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4k0UG6iutubJZOelhCwlqK'},
        {'category': category5, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4k0UG6iutubJZOQNPOki3M'},
        {'category': category5, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4k0UG6iutubJZORggD57Df'},
        {'category': category6, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4ivLG6iutubJZOxU1vSbYa'},
        {'category': category6, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4kHSG6iutubJZOm3jMh062'},
        {'category': category6, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4kHSG6iutubJZOBmSxZgp6'},
        {'category': category6, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kHSG6iutubJZOzR2wW9ET'},
        {'category': category6, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kHSG6iutubJZOrVEVrNd0'},
        {'category': category6, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kHSG6iutubJZOGq6vAOwI'},
        {'category': category7, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4ivsG6iutubJZOxrUT6Jyt'},
        {'category': category7, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4kYPG6iutubJZOnIxc8KHp'},
        {'category': category7, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4kYPG6iutubJZOgcIoIulL'},
        {'category': category7, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kYPG6iutubJZO5jOyednQ'},
        {'category': category7, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kYPG6iutubJZOObDlLLm4'},
        {'category': category7, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kYPG6iutubJZO5CkkPwR1'},
        {'category': category8, 'number_of_books': 1,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4ivsG6iutubJZOxrUT6Jyt'},
        {'category': category8, 'number_of_books': 2,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4kYPG6iutubJZOnIxc8KHp'},
        {'category': category8, 'number_of_books': 3,
            'subscription_type': 'Monthly', 'stripe_price_id': 'price_1P4kYPG6iutubJZOgcIoIulL'},
        {'category': category8, 'number_of_books': 1,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kYPG6iutubJZO5jOyednQ'},
        {'category': category8, 'number_of_books': 2,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kYPG6iutubJZOObDlLLm4'},
        {'category': category8, 'number_of_books': 3,
            'subscription_type': '3-Months', 'stripe_price_id': 'price_1P4kYPG6iutubJZO5CkkPwR1'},
    ]

    # Update existing entries or create new ones
    for option_data in new_or_updated_subscription_options:
        subscription_option, created = SubscriptionOption.objects.update_or_create(
            category=option_data['category'],
            number_of_books=option_data['number_of_books'],
            subscription_type=option_data['subscription_type'],
            defaults={
                'stripe_price_id': option_data['stripe_price_id']
            }
        )
        if created:
            print(f"Created new SubscriptionOption: {subscription_option}")
        else:
            print(f"Updated existing SubscriptionOption: {subscription_option}")


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20240413_1126'),  # previous migration file  # noqa
    ]

    operations = [
        migrations.RunPython(add_subscription_options),
    ]
