# Generated by Django 3.2.23 on 2024-03-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_rating'),
        ('subscriptions', '0007_auto_20240328_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='number_of_books',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='plan',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic (2 books)'), ('standard', 'Standard (3 books)'), ('premium', 'Premium (4 books)')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptionoption',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category'),
        ),
        migrations.AlterField(
            model_name='usersubscriptionoption',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscriptionoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
