# Generated by Django 3.2.23 on 2024-04-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20240413_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoption',
            name='subscription_type',
            field=models.CharField(choices=[('one-off', 'One-off'), ('monthly', 'Monthly'), ('three_months', '3-Months')], max_length=20),
        ),
    ]
