# Generated by Django 3.2.23 on 2024-03-31 14:07

from django.db import migrations, models


def convert_plan_name_to_int(apps, schema_editor):
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    mapping = {'basic': 1, 'standard': 2, 'premium': 3}
    for plan in SubscriptionPlan.objects.all():
        plan.name = mapping[plan.name]
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        # replace with your previous migration
        ('subscriptions', '0007_auto_20240328_1825'),
    ]

    operations = [
        migrations.RunPython(convert_plan_name_to_int),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.IntegerField(choices=[(
                1, 'Basic (2 books)'), (2, 'Standard (3 books)'), (3, 'Premium (4 books)')]),
        ),
    ]
