# Generated by Django 3.2.23 on 2024-05-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscriptionoption_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionoption',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
