# Generated by Django 3.2.23 on 2024-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_usersubscriptionoption_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionoption',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptionoption',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
