# Generated by Django 3.2.23 on 2024-03-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20240331_1407'),
        ('subscriptions', '0009_auto_20240331_1529'),
    ]

    operations = [
    ]
